---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Main Stack

Parameters:
  ArtifactBucket:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - ArtifactBucket
    ParameterLabels:
      ArtifactBucket:
        default: Artifact Bucket

Resources:
  SQS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/sqs.yml
  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func
      Handler: index.handler
      Runtime: python2.7
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: SQSSendMessagePolicy
              Effect: Allow
              Action: sqs:SendMessage
              Resource: !GetAtt SQS.Outputs.QueueArn
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: !Sub s3://${ArtifactBucket}/dead-letter-queue.yml
  CustomDeadLetterQueue:
    Type: Custom::DeadLetterQueue
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt LambdaDeadLetterQueue.Arn
      FunctionName: !Ref Func
      TargetArn: !GetAtt SQS.Outputs.QueueArn

Outputs:
  FuncName:
    Value: !Ref Func
